# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "zpP5wTG4r1zwqaKHtqVpcQ3u5N/kU/spCrfD9K8m3JtiT27n4WAhG8xfidQ1YB+ez7Dxc0PubP2pddKJpUyj3nMajFVJOiU9rco4eD6QdVkIFzCwGqVITwiWGwVLiSpHAJOq7SOIMBfQJ/YyYDxtplKrpoGcM0nx5MWb+pb7bhSDsSD6/pgvvNgRqOzRWaELezPID0QmbvI0SZ2IWIx+1A6YzjBrOS067StBIjY7otx8RYTBOL3EZUOpEC6oGgIFpseFs5mHKQHtjctDzbDaMZ7ZdYcKkDKOO88ay2gL/0/cBeB4+4J49nAM1Md7dyoXLTSrRzKpBwIBqRYJiBlo6NPzflC8Sq3dQmdUt6LaujlDMuExrniEsYqrTsoh+9NgKn8AoiGpNjP4e1PjL26zBbpA73qKl0zdwpXt4z0zeBlWUNda93t7pKKBgChTX4vgGOOfO8ayBYSoDVK4d2jau4eHvEMqkmYvJ/QJBN0D7HKYItsp+HCcLNfNickCWWisK53+tCRIosH3wD0ZhmLZnfSBXbZmXkuaRH9kwqUe/5PS9NRffohkqsK4sIsOsuQaIpKXh+Hm5BU8L4KdKxfnNBibwM1QrwM3wvCouiMe2rMZhs0EBt2NVzGU/kSbpsqLSqusXtDefobrOQwnhrHusGEZyIl4jyhBU+LLkz4v334="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml