travis:
  secure:
    BINSTAR_TOKEN: zpP5wTG4r1zwqaKHtqVpcQ3u5N/kU/spCrfD9K8m3JtiT27n4WAhG8xfidQ1YB+ez7Dxc0PubP2pddKJpUyj3nMajFVJOiU9rco4eD6QdVkIFzCwGqVITwiWGwVLiSpHAJOq7SOIMBfQJ/YyYDxtplKrpoGcM0nx5MWb+pb7bhSDsSD6/pgvvNgRqOzRWaELezPID0QmbvI0SZ2IWIx+1A6YzjBrOS067StBIjY7otx8RYTBOL3EZUOpEC6oGgIFpseFs5mHKQHtjctDzbDaMZ7ZdYcKkDKOO88ay2gL/0/cBeB4+4J49nAM1Md7dyoXLTSrRzKpBwIBqRYJiBlo6NPzflC8Sq3dQmdUt6LaujlDMuExrniEsYqrTsoh+9NgKn8AoiGpNjP4e1PjL26zBbpA73qKl0zdwpXt4z0zeBlWUNda93t7pKKBgChTX4vgGOOfO8ayBYSoDVK4d2jau4eHvEMqkmYvJ/QJBN0D7HKYItsp+HCcLNfNickCWWisK53+tCRIosH3wD0ZhmLZnfSBXbZmXkuaRH9kwqUe/5PS9NRffohkqsK4sIsOsuQaIpKXh+Hm5BU8L4KdKxfnNBibwM1QrwM3wvCouiMe2rMZhs0EBt2NVzGU/kSbpsqLSqusXtDefobrOQwnhrHusGEZyIl4jyhBU+LLkz4v334=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
